kalman_arguments:
    KALMAN_PROCESS_NOISE_AMOUNT: 1
    KALMAN_MEASUREMENT_NOISE_AMOUNT_XY:  1e-3
    KALMAN_MEASUREMENT_NOISE_AMOUNT_Z: 1

parameters:
    # SIMULATION_MODE = "use_airsim", "saved_simulation"
    SIMULATION_MODE: "use_airsim"

    # run_loc = "server", "local"
    run_loc: "local"

    USE_TRACKBAR: False

    # LOOP_MODE = 0-normal_simulation, teleport_simulation, 1-openpose, 2-toy_example, 3-create_dataset, 4- save_gt_poses 5-calibration
    LOOP_MODE: "calibration"

    #hessian_part: 0-future, 1-middle, 2-whole
    hessian_part: "whole"
    #uncertainty_calc_method: 0-sum_eig 1-add_diag 2-multip_eig 3-determinant 4-max_eig 5-root_six
    uncertainty_calc_method: "sum_eig"

    #about toy example mode
    FIND_BEST_TRAJ: False
    NUM_OF_NOISE_TRIALS: 5

    PREDEFINED_TRAJ_LEN: 0  
    LENGTH_OF_SIMULATION: 150

    PORT: 41452

    FILE_NAMES: ""
    FOLDER_NAMES: ""

energy_parameters:
    #lift_method: "simple", "complex"
    LIFT_METHOD: "simple"
    #bone_len_method: "no_sqrt", "sqrt"
    BONE_LEN_METHOD: "sqrt"
    #smoothness_mode: 0-velocity, 1-position, 2-all_connected, 3-only_velo_connected, 4-none
    SMOOTHNESS_MODE: "velocity"
    #projection_method: "scaled, normal, normalized"
    PROJECTION_METHOD: "normal"

    ESTIMATION_WINDOW_SIZE: 5
    FUTURE_WINDOW_SIZE: 3

    CALIBRATION_WINDOW_SIZE: 20
    PREDEFINED_MOTION_MODE_LENGTH: 10

    PARAM_FIND_M: False
    PARAM_READ_M: False

    QUIET: False

    #mode_3d: 0- gt, 1- naiveback, 2- energy pytorch, 3-energy scipy
    #mode_2d: 0- gt, 1- gt_with_noise, 2- openpose
    #mode_lift: 0- gt, 1- gt_with_noise, 2-lift
    #bone_len: 0-gt, 1- calib_res
    MODES: 
        mode_3d: "scipy"
        mode_2d: "gt_with_noise"
        mode_lift: "gt_with_noise"
        bone_len: "calib_res"

    MODEL: "mpi"
    METHOD: "trf"
    FTOL: 0.001
     
    WEIGHTS: 
        proj: 0.001
        smooth: 1
        bone: 1 
        lift: 0.05

    WEIGHTS_FUTURE:
        proj: 0.001
        smooth: 1
        bone: 1 
        lift: 0.05

    #init_pose_mode: 0- "gt", "zeros", "backproj", "gt_with_noise"
    INIT_POSE_MODE: "backproj"
    
    NOISE_2D_STD: 3
    NOISE_LIFT_STD:  0.05
    NOISE_3D_INIT_STD:  0.5
    DRONE_POS_JITTER_NOISE_STD: 0.5

    USE_SYMMETRY_TERM: True
    USE_SINGLE_JOINT: False

    USE_TRAJECTORY_BASIS: False
    NUMBER_OF_TRAJ_PARAM: 5

    #modes: 0- "constant", "adaptive"
    RECONSTRUCTION_ENERGY: "constant"
    UNCERTAIN_ENERGY: "constant"

    USE_LIFT_TERM: True
    USE_BONE_TERM: True

    ANIMATION_NUM: 0
    SEED: 0
    EXPERIMENT_NAME: ""

active_parameters:
    #hessian_part: 0-future, 1-middle, 2-whole
    HESSIAN_PART: "whole"
    #uncertainty_calc_method: 0-sum_eig 1-add_diag 2-multip_eig 3-determinant 4-max_eig 5-root_six
    UNCERTAINTY_CALC_METHOD: "sum_eig"
    #Minnmax: True-min, False-max
    MINMAX: True
    
    GO_DISTANCE: 0.5
    LOOKAHEAD: 0.5

    UPPER_LIM: -3 
    LOWER_LIM: -0.5
    UPDOWN_LIM: [-3, -0.5]
    WOBBLE_FREQ: 0.5
    Z_POS: -2.5
    TRAJECTORY: "active"
    
    #active_sampling = "ellipse", "uniform"
    ACTIVE_SAMPLING_MODE: "uniform"
    TOP_SPEED: 3 
    DELTA_T: 0.05