kalman_arguments:
    KALMAN_PROCESS_NOISE_AMOUNT: 1
    KALMAN_MEASUREMENT_NOISE_AMOUNT_XY:  5*1e-4
    KALMAN_MEASUREMENT_NOISE_AMOUNT_Z: 1

parameters:
    # SIMULATION_MODE = "use_airsim", "saved_simulation"
    SIMULATION_MODE: "use_airsim"

    # run_loc = "server", "local"
    run_loc: "server"
    USE_TRACKBAR: False

    # LOOP_MODE = 0-flight_simulation, teleport_simulation, 2-toy_example, 3-create_dataset, 4- save_gt_poses , 5-openpose_liftnet
    LOOP_MODE: "teleport_simulation"
    # CALIBRATION_MODE
    CALIBRATION_MODE: True

    #about toy example mode
    FIND_BEST_TRAJ: False
    NUM_OF_NOISE_TRIALS: 5

    LENGTH_OF_SIMULATION: 80

    FILE_NAMES: ""
    FOLDER_NAMES: ""

energy_parameters:
    #lift_method: "simple", "complex"
    LIFT_METHOD: "simple"
    #bone_len_method: "no_sqrt", "sqrt"
    BONE_LEN_METHOD: "sqrt"
    #smoothness_mode: 0-velocity, 1-position, 2-all_connected, 3-only_velo_connected, 4-none
    SMOOTHNESS_MODE: "position"
    #projection_method: "scaled, normal, normalized"
    PROJECTION_METHOD: "normalized"

    ESTIMATION_WINDOW_SIZE: 8
    FUTURE_WINDOW_SIZE: 1
    PREDEFINED_MOTION_MODE_LENGTH: 8

    CALIBRATION_WINDOW_SIZE: 100


    PARAM_FIND_M: False
    PARAM_READ_M: False

    QUIET: False

    #mode_3d: 0- gt, 1- naiveback, 3-energy scipy
    #mode_2d: 0- gt, 1- gt_with_noise, 2- openpose
    #mode_lift: 0- gt, 1- gt_with_noise, 2-lift
    #bone_len: 0-gt, 1- calib_res
    MODES: 
        mode_3d: "scipy"
        mode_2d: "openpose"
        mode_lift: "lift"
        bone_len: "calib_res"
        mode_future: "scipy"

    MODEL: "mpi"
    METHOD: "trf"
    FTOL: 0.0001
    XTOL: 0.00000001
     
    WEIGHTS_CALIB: 
        proj: 0.8
        sym: 0.2

    WEIGHTS: 
        proj: 0.0001
        smooth: 1
        bone: 1
        lift: 1

    WEIGHTS_FUTURE:
        proj: 0.0001
        smooth: 1
        bone: 0
        lift: 1

    #init_pose_mode: "gt", "zeros", "backproj", "gt_with_noise", "initial_optimization"
    INIT_POSE_MODE: "initial_optimization"
    
    NOISE_2D_STD: 3
    NOISE_LIFT_STD:  0.05
    NOISE_3D_INIT_STD:  0.5
    DRONE_POS_JITTER_NOISE_STD: 0.5

    USE_SYMMETRY_TERM: True
    USE_SINGLE_JOINT: False

    USE_TRAJECTORY_BASIS: False
    NUMBER_OF_TRAJ_PARAM: 5

    #modes: 0- "constant", "adaptive"
    RECONSTRUCTION_ENERGY: "constant"
    UNCERTAIN_ENERGY: "constant"

    USE_LIFT_TERM: True
    USE_BONE_TERM: True

    ANIMATION_NUM: 0
    SEED: 0
    EXPERIMENT_NAME: ""

active_parameters:
    #hessian_part: 0-future, 1-middle, 2-whole
    HESSIAN_PART: "whole"
    #uncertainty_calc_method: 0-sum_eig 1-add_diag 2-multip_eig 3-determinant 4-max_eig 5-root_six
    UNCERTAINTY_CALC_METHOD: "sum_eig"
    #Minnmax: "use_min", "use_max"
    MINMAX: use_min
    #USE_HESSIAN_MODE: "whole" "partial"
    USE_HESSIAN_MODE: "whole"

    #velocity, position
    MOVEMENT_MODE: "velocity"
    
    LOOKAHEAD: 0.8

    SAFE_RADIUS: 7

    UPPER_LIM: -3 
    LOWER_LIM: -0.5
    UPDOWN_LIM: [-3, -0.5]
    WOBBLE_FREQ: 0.5
    Z_POS: -2.5

    #active_sampling = "ellipse", "uniform"
    ACTIVE_SAMPLING_MODE: "uniform"
    TOP_SPEED: 4
    DELTA_T: 0.2
    DIRECTION_DISTANCE: 3

    ACC_MAX: 
        'x_y': 3.1 
        'z': 1.3
    ACC_ALPHA: 0.9